// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "src/api/data/adresses.json" {
  const addressList: {
    postNumber: number;
    city: string;
    street: string;
    typeCode: 1 | 2 | 3 | 4 | 5 | 6;
    type:
      | "Firma/organisasjon med eige postnummer"
      | "Gate-/veg-adresse"
      | "Kjend stadnamn"
      | "Postboksadresse"
      | "Postboksar (tidl Serviceboks)"
      | "Stadnamn med postnummer";
    district: string;
    municipalityNumber: number;
    municipality: string;
    county: string;
  }[];
  export default addressList;
}
